package rclone

type BackendField struct {
	Name     string   `json:"name"`              // rclone option name, e.g. "host"
	Label    string   `json:"label,omitempty"`   // translation key, e.g. "cloud.rclone.sftp.host"
	Kind     string   `json:"kind"`              // "text" | "password" | "number" | "select" | "checkbox"
	Required bool     `json:"required,omitempty"`
	Default  string   `json:"default,omitempty"`
	Options  []string `json:"options,omitempty"` // for Kind == "select"
	Obscure  bool     `json:"obscure,omitempty"` // pass opt.obscure = true for this field's value?

	// For stateful backends like Proton Drive:
	Generated bool `json:"generated,omitempty"` // rclone fills this after first auth; restored on reregister, never user-input
	Transient bool `json:"transient,omitempty"` // user supplies but never persisted (e.g. TOTP codes that expire in 30s)
}

type Backend struct {
	ID     string         `json:"id"`     // "sftp", "webdav", "s3", "dropbox", "onedrive"
	Type   string         `json:"type"`   // the rclone backend type; usually equals ID
	Fields []BackendField `json:"fields"`
}

var Backends = []Backend{
	{
		ID: "sftp", Type: "sftp",
		Fields: []BackendField{
			{Name: "host", Kind: "text", Required: true},
			{Name: "port", Kind: "number", Default: "22"},
			{Name: "user", Kind: "text", Required: true},
			{Name: "pass", Kind: "password", Obscure: true},
			{Name: "key_file", Kind: "text"},
			{Name: "key_file_pass", Kind: "password", Obscure: true},
		},
	},
	{
		ID: "webdav", Type: "webdav",
		Fields: []BackendField{
			{Name: "url", Kind: "text", Required: true},
			{Name: "vendor", Kind: "select", Default: "nextcloud",
				Options: []string{"nextcloud", "owncloud", "sharepoint", "other"}},
			{Name: "user", Kind: "text"},
			{Name: "pass", Kind: "password", Obscure: true},
		},
	},
	{
		ID: "s3", Type: "s3",
		Fields: []BackendField{
			{Name: "provider", Kind: "select", Required: true,
				Options: []string{"AWS", "Backblaze", "Cloudflare", "Minio", "Other"}},
			{Name: "access_key_id",     Kind: "text",     Required: true},
			{Name: "secret_access_key", Kind: "password", Required: true},
			{Name: "region",            Kind: "text",     Default: "us-east-1"},
			{Name: "endpoint",          Kind: "text"},
			// bucket is not a backend field — it is part of the path. The frontend collects it and we prepend it to the folder path.
		},
	},
	{
		ID: "dropbox", Type: "dropbox",
		// No fields — uses rclone's interactive auth. Not implemented in v1;
		// the wizard greys out Dropbox until we implement the OAuth-in-rclone flow.
		Fields: []BackendField{},
	},
	{
		ID: "onedrive", Type: "onedrive",
		Fields: []BackendField{},
	},
	{
		ID: "protondrive", Type: "protondrive",
		Fields: []BackendField{
			// User-input
			{Name: "username",         Kind: "text",     Required: true},
			{Name: "password",         Kind: "password", Required: true, Obscure: true},
			{Name: "2fa",              Kind: "text",     Transient: true}, // 6-digit TOTP, never stored
			{Name: "mailbox_password", Kind: "password", Obscure: true},   // legacy accounts only

			// Generated by rclone after successful initial auth — restored on
			// reregister so the user never re-enters 2FA. NOT shown in the form.
			{Name: "client_uid",             Kind: "password", Obscure: true, Generated: true},
			{Name: "client_access_token",    Kind: "password", Obscure: true, Generated: true},
			{Name: "client_refresh_token",   Kind: "password", Obscure: true, Generated: true},
			{Name: "client_salted_key_pass", Kind: "password", Obscure: true, Generated: true},
		},
	},
}

func FindBackend(id string) *Backend {
	for i := range Backends {
		if Backends[i].ID == id {
			return &Backends[i]
		}
	}
	return nil
}
